version: '3.1'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    restart: unless-stopped
    command: start-dev
    networks:
      - keycloak

networks:
  keycloak:
    driver: bridge