version: "3.1"

services:

  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql:/bitnami/mysql
      - ./my.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
    networks:
      - canal

  canal-server:
    image: canal/canal-server:v1.1.5
    depends_on:
     - mysql
    environment:
      - canal.instance.mysql.slaveId=1233
      - canal.auto.scan=false
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=123
      - canal.instance.filter.regex=.*\\..*
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.destinations=data_pipe
      - canal.serverMode=tcp
      - canal.mq.servers=192.168.12.53:9092
      - canal.mq.topic=kafkatest
      - canal.mq.partition=0
    ports:
      - 11111:11111
    volumes:
      - canal:/home/admin/canal-server/logs/
    restart: unless-stopped
    networks:
      - canal

networks:
  canal:
    driver: bridge

volumes:
  canal:
  mysql: