version: "3.1"

services:

  zookeeper:
    image: bitnami/zookeeper:3.7.0
    ports:
      - '2181:2181'
    volumes:
      - zookeeper:/bitnami/zookeeper
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    networks:
      - canal

  kafka:
    image: bitnami/kafka:2.2.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - kafka:/bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_MAX_REQUEST_SIZE=1073741824
    restart: unless-stopped
    networks:
      - canal

  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql:/bitnami/mysql
      - ./mysql/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
    networks:
      - canal

  canal-server:
    image: canal/canal-server:v1.1.5
    depends_on:
     - mysql
     - kafka
    environment:
      - canal.auto.scan=false
      - canal.serverMode=kafka
      - kafka.bootstrap.servers=kafka:9092
      - canal.instance.mysql.slaveId=1233
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=123
      - canal.instance.filter.regex=.*\\..*
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.destinations=data_pipe
      - canal.mq.topic=kafkatest
      - canal.mq.partition=0
    ports:
      - 11111:11111
    volumes:
      - canal:/home/admin/canal-server/logs/
    restart: unless-stopped
    networks:
      - canal

networks:
  canal:
    driver: bridge

volumes:
  zookeeper:
  kafka:
  canal:
  mysql: