version: "3.1"

services:
  mysql:
    image: bitnami/mysql:8.0
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql:/bitnami/mysql
      - /tmp/docker/mysql/my.cnf:/opt/bitnami/mysql/conf/my_custom.cnf:ro
    networks:
      - canal

  canal-server:
    image: canal/canal-server:v1.1.5
    environment:
      - canal.auto.scan=false
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.instance.filter.regex=.*\\..*
      - canal.destinations=test
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
    ports:
      - 11111:11111
    volumes:
      - canal:/home/admin/canal-server/logs/
    restart: unless-stopped
    networks:
      - canal

networks:
  canal:
    driver: bridge

volumes:
  canal:
  mysql: