

services:

  trino:
    image: trinodb/trino:386
    hostname: my-localhost-trino
    user: root
    container_name: my-localhost-trino
    entrypoint: /root/docker-entrypoint.sh
    networks:
      - trino
    volumes:
      - ./trino/install.properties:/root/install.properties
      - ./trino/docker-entrypoint.sh:/root/docker-entrypoint.sh
    ports:
      - 8080:8080



networks:
  trino:
    driver: bridge