version: "3.1"

services:

  jobmanager:
    image: flink:1.13.6-scala_2.12-java8
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
    ports:
      - 8081:8081
    command: jobmanager
    volumes:
      - jobmanager:/flink/jobmanager
      - ./seatunnel-connector-flink-jdbc-2.0.5-SNAPSHOT.jar:/opt/flink/usrlib/seatunnel-connector-flink-jdbc-2.0.5-SNAPSHOT.jar
      - ./seatunnel-connector-flink-file-2.0.5-SNAPSHOT.jar:/opt/flink/usrlib/seatunnel-connector-flink-file-2.0.5-SNAPSHOT.jar
    networks:
      - flink
  taskmanager:
    image: flink:1.13.6-scala_2.12-java8
    depends_on:
      - jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
    command: taskmanager
    scale: 1
    volumes:
      - taskmanager:/flink/taskmanager
      - ./seatunnel-connector-flink-jdbc-2.0.5-SNAPSHOT.jar:/opt/flink/usrlib/seatunnel-connector-flink-jdbc-2.0.5-SNAPSHOT.jar
      - ./seatunnel-connector-flink-file-2.0.5-SNAPSHOT.jar:/opt/flink/usrlib/seatunnel-connector-flink-file-2.0.5-SNAPSHOT.jar
    networks:
      - flink

networks:
  flink:
    driver: bridge

volumes:
  jobmanager:
  taskmanager: