version: '3.1'

services:

  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-cn-0pp1lyas2000m69gj.elasticsearch.aliyuncs.com:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elas88ticDevDEVM
    restart: unless-stopped
    ports:
      - 5601:5601