version: '3.1'

services:

  zookeeper:
    image: bitnami/zookeeper:3.7.0
    ports:
      - '2181:2181'
    volumes:
      - zookeeper:/bitnami/zookeeper
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: unless-stopped
    networks:
      - kafka

  kafka:
    image: bitnami/kafka:2.2.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - kafka:/bitnami/kafka
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    restart: unless-stopped
    networks:
      - kafka

  eagle:
    image: nickzurich/kafka-eagle:2.0.8
    depends_on:
      - kafka
    ports:
      - '8048:8048'
    environment:
      - EFAK_CLUSTER_ZK_LIST=zookeeper:2181
    networks:
      - kafka
#  eagle:
#    build:
#      context: .
#    environment:
#      EFAK_CLUSTER_ZK_LIST: zookeeper:2181
#    depends_on:
#      - kafka
#    ports:
#      - 8048:8048

networks:
  kafka:
    driver: bridge

volumes:
  zookeeper:
  kafka: