version: "3.1"

services:
  gerrit:
    image: gerritcodereview/gerrit:3.4.3
    ports:
      - 8080:8080
      - 29418:29418
    networks:
      - gerrit
#    command:
#      - init

networks:
  gerrit:
    driver: bridge