version: '3'

# https://github.com/big-data-europe/docker-hadoop

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    env_file:
      - ./hadoop.env
    environment:
      - CLUSTER_NAME=docker
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9870
    ports:
      - 9864:9864
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hadoop

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864
    ports:
      - 8088:8088
      - 8032:8032
      - 8030:8030
      - 8031:8031
    networks:
      - hadoop

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088
    ports:
      - 8042:8042
    networks:
      - hadoop

  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    env_file:
      - ./hadoop.env
    environment:
      - SERVICE_PRECONDITION=namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088
    ports:
      - 19888:19888
      - 8188:8188
    volumes:
      - historyserver:/hadoop/yarn/timeline
    networks:
      - hadoop

volumes:
  datanode:
  namenode:
  historyserver:

networks:
  hadoop: