version: '3'

# https://github.com/big-data-europe/docker-hadoop
# https://github.com/big-data-europe/docker-hadoop/issues/98
services:
  namenode:
    image: apache/hadoop:3
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - hadoop

networks:
  hadoop: