version: '3'
services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=maxkey
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/mysqld.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
      - ./mysql/init.d:/docker-entrypoint-initdb.d

  maxkey-frontend:
    image: maxkeytop/maxkey-frontend:3.5.1
    container_name: maxkey-frontend
    environment:
      - TZ:Asia/Shanghai
    ports:
      - 8527:8527

  maxkey:
    image: maxkeytop/maxkey:3.5.1
    container_name: maxkey
    environment:
      - TZ:Asia/Shanghai
      - DATABASE_HOST:localhost
      - DATABASE_PORT:3306
      - DATABASE_NAME:maxkey
      - DATABASE_USER:root
      - DATABASE_PWD:maxkey
    ports:
      - 9527:9527

  maxkey-mgt:
    image: maxkeytop/maxkey-mgt:3.5.1
    container_name: maxkey-mgt
    environment:
      - TZ:Asia/Shanghai
      - DATABASE_HOST:localhost
      - DATABASE_PORT:3306
      - DATABASE_NAME:maxkey
      - DATABASE_USER:root
      - DATABASE_PWD:maxkey
    ports:
      - 9526:9526

  maxkey-mgt-frontend:
    image: maxkeytop/maxkey-mgt-frontend:3.5.1
    container_name: maxkey-mgt-frontend
    environment:
      - TZ:Asia/Shanghai
    ports:
      - 8526:8526
      
  maxkey-nginx:
    image: maxkey:maxkey-nginx
    container_name: nginx
    build: ./docker-nginx
    ports:
      - 80:80