version: "3.1"

services:

  hop:
    image: apache/hop:1.2.0-SNAPSHOT
    environment:
      - HOP_SERVER_PORT:8080
    ports:
      - 8080:8080
    networks:
      - hop
  hop-web:
    image: apache/hop-web:1.2.0-SNAPSHOT
    depends_on:
      - hop
    networks:
      - hop

networks:
  hop:
    driver: bridge