version: '3'

services:
  # 配置 dinky 后端服务
  dinky-server:
    image: sivacohan/dinky-server:lastest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/dlink?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    depends_on:
      - database
    restart: unless-stopped

  # 配置 dinky web 界面
  dinky-web:
    image: sivacohan/dinky-web:lastest
    environment:
      API_HOST: dinky-server
      API_PORT: 8888
    ports:
      - "8080:80"
    depends_on:
      - dinky-server
      - database

  # 配置 mysql5.7 数据库
  database:
    image: sivacohan/dinky-mysql-server:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dlink
      MYSQL_USER: dlink
      MYSQL_PASSWORD: dlink
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped